-- AlterTable
ALTER TABLE "Order" ALTER COLUMN "total" SET DEFAULT 0.00,
ALTER COLUMN "total" SET DATA TYPE DECIMAL(65,30);

-- AlterTable
ALTER TABLE "OrderItem" ALTER COLUMN "quantity" SET DATA TYPE DECIMAL(65,30);
